AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  TestAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: anni
      DefinitionUri: test-swagger.json
    
Outputs:

    TestAPI:
      Description: "Root API endpoint URL for anni stage"
      Value: !Sub "https://${TestAPI}.execute-api.${AWS::Region}.amazonaws.com/anni"
      Export:
        Name: TestAPIRoot
